Repository demikernel/inetstack, pull requests merged in 2021-06, with the labels that each got.

#1 Fixing Broken Build
  Cargo.toml
  rust-toolchain
  src/collections/waker_page.rs
  src/lib.rs
Labels: bug

#2 Fixing Build Warnings
  src/collections/async_slab.rs
  src/collections/hashttlcache/mod.rs
  src/lib.rs
  src/protocols/tcp/peer.rs
Labels: bug

#8 ARP Cache Refactor
  src/protocols/arp/cache/mod.rs
  src/protocols/arp/cache/tests.rs
Labels: bug, enhancement

#10 Refactoring Implementation of Mutable and Non-Mutable Buffers
  src/collections/bytes.rs
  src/protocols/tcp/established/state/receiver.rs
  src/protocols/tcp/tests/mod.rs
  src/sync/mod.rs
  src/test_helpers.rs
  tests/tcp_loop.rs
  tests/udp_echo.rs
  tests/udp_loop.rs
Labels: enhancement

#13 Dropping Tracy Client
  Cargo.toml
  src/engine.rs
  src/libos.rs
  src/scheduler.rs
  tests/tcp_loop.rs
  tests/udp_echo.rs
  tests/udp_loop.rs
Labels: enhancement

#14 Dropping Unneeded Type Casts
  src/collections/waker_page.rs
  src/protocols/icmpv4/peer.rs
  src/protocols/tcp/active_open.rs
  src/protocols/tcp/passive_open.rs
Labels: bug

#15 Dropping Redundant Slicing
  src/protocols/ipv4/datagram.rs
  src/protocols/tcp/segment.rs
Labels: bug

#16 Unneeded Return Statement
  src/file_table.rs
  src/protocols/tcp/peer.rs
Labels: bug

#17 Missing Implementation for Default Trait
  src/collections/async_map.rs
  src/file_table.rs
  src/scheduler.rs
  src/sync/threadunsafe.rs
Labels: bug

#19 Don't Using Map Unit Function
  src/protocols/tcp/active_open.rs
  src/protocols/tcp/established/state/receiver.rs
  src/protocols/tcp/passive_open.rs
  src/protocols/udp/peer.rs
Labels: bug

#20 Bad Structure Initialization
  src/protocols/icmpv4/peer.rs
  src/protocols/ipv4/peer.rs
  src/protocols/udp/peer.rs
Labels: bug

#21 Fixing Various Build Warnings
  src/collections/waker_page.rs
  src/protocols/ip/port.rs
  src/protocols/tcp/segment.rs
  src/protocols/udp/peer.rs
  src/runtime.rs
  src/scheduler.rs
Labels: bug

#22 Don't Use Clone When Copying is Available
  src/protocols/tcp/active_open.rs
  src/protocols/tcp/established/mod.rs
  src/protocols/tcp/passive_open.rs
  src/protocols/tcp/peer.rs
  src/test_helpers.rs
Labels: bug

#11 Improvements on ARP Layer
  src/engine.rs
  src/protocols/arp/cache/mod.rs
  src/protocols/arp/cache/tests.rs
  src/protocols/arp/mod.rs
  src/protocols/arp/msg/mod.rs
  src/protocols/arp/options.rs
  src/protocols/arp/pdu/mod.rs
  src/protocols/arp/peer.rs
  src/protocols/arp/tests.rs
  src/test_helpers.rs
  tests/udp_echo.rs
Labels: bug, enhancement

#24 Replacing `gen-iter` for `bit-iter`
  Cargo.toml
  src/scheduler.rs
Labels: enhancement

#25 Updating Dependencies
  Cargo.toml
  src/logging.rs
  src/runtime.rs
  src/test_helpers.rs
  tests/udp_echo.rs
Labels: enhancement

#27 Deny Warnings
  .gitignore
  src/lib.rs
  src/protocols/arp/options.rs
  src/protocols/tcp/options.rs
  src/test_helpers.rs
Labels: bug, enhancement

#29 Disabling ARP Cache Eviction
  src/protocols/arp/peer.rs
Labels: bug

#30 Workaround for `tcp_connect` Test
  src/protocols/tcp/established/background/mod.rs
  src/protocols/tcp/tests/mod.rs
  src/test_helpers.rs
Labels: bug
